name: Build and Push Container Image

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * 0" # Weekly on Sundays at 01:00
  push:
    branches:
      - main
    paths:
      - 'container/Containerfile'
      - '.github/workflows/build-container.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'container/Containerfile'
      - '.github/workflows/build-container.yaml'
env:
  REGISTRY: quay.io
  IMAGE_NAME: skodjob/strimzi-systemtest

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.SKODJOB_QUAY_USERNAME }}
          password: ${{ secrets.SKODJOB_QUAY_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push container image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./container/Containerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false